modules+=("core")
commands+=("list"
	   "search->list"
	   "install"
	   "remove"
	   "update"
	   "upgrade"
	   "garbage-collect->garbage_collect"
	   "build"
	   "shell"
	   "help")
default_command="help"
